Importing Important Libraries....


In [31]:
import pandas as pd
import numpy as np

Importing Important Dataset files....

In [32]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

Printing the Keys Present in the IRIS dataset....

In [33]:
print("Keys Of IRIS dataset: \n{}".format(iris_dataset.keys()))

Keys Of IRIS dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


Key dataset Description(DESCR)....

In [34]:
value = iris_dataset['DESCR']
start_value = value[:190]
print(start_value + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, 
...


Printing key Target Names....

In [35]:
print("Target Names: {}".format(iris_dataset['target_names']))

Target Names: ['setosa' 'versicolor' 'virginica']


Printing the types of Features Names present in IRIS Dataset....

In [36]:
print("Feature Names: \n {}".format(iris_dataset['feature_names']))

Feature Names: 
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Printing type of data Present....

In [37]:
print("Type Of DATA : {}".format(type(iris_dataset['data'])))

Type Of DATA : <class 'numpy.ndarray'>


Printing the shape Of DATA Present ....

In [38]:
print("Shape Of DATA : {}".format(iris_dataset['data'].shape))

Shape Of DATA : (150, 4)


How the dataset looks like Example of first 20 ROWS....

In [39]:
print("First 20 Rows of DATASET: \n{}".format(iris_dataset['data'][:20]))

First 20 Rows of DATASET: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]]


Printing the type of target key....

In [40]:
print("Type of Target: {}".format(type(iris_dataset['target'])))

Type of Target: <class 'numpy.ndarray'>


Printing the shape of target datakey....

In [41]:
print("Shape Of Target: {}".format(iris_dataset['target'].shape))

Shape Of Target: (150,)


Printing the Target Dataset....

In [42]:
print("Target:\n{}".format(iris_dataset['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Importing train_test_split from model selection of sklearn....

In [43]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(
              iris_dataset['data'], iris_dataset['target'], random_state = 0)

Printing the Tuple Returned from train_test_split....

In [44]:
print("X_train shape: {}".format(Xtrain.shape))
print("Y_train shape: {}".format(Ytrain.shape))
print("X_test shape: {}".format(Xtest.shape))
print("Y_test shape: {}".format(Ytest.shape))

X_train shape: (112, 4)
Y_train shape: (112,)
X_test shape: (38, 4)
Y_test shape: (38,)


Implementing K Nearest Neighbors....

In [48]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [49]:
knn.fit(Xtrain, Ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

Example Using for checking accuracy by new shape....

In [50]:
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape : {}".format(X_new.shape))

X_new.shape : (1, 4)


Doing the Predictions....

In [51]:
prediction = knn.predict(X_new)

print("Prediction : {}".format(prediction))
print("Predicted Target Name: {}".format(iris_dataset['target_names'][prediction]))

Prediction : [0]
Predicted Target Name: ['setosa']


Printing the Complete Predictions Set....

In [53]:
y_pred = knn.predict(Xtest)
print("Test Set Predictions: \n {}".format(y_pred))

Test Set Predictions: 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


Printing the Accuracy Of Project.... #Result

> Indented block



In [54]:
print("Test Set Score: {}".format(np.mean(y_pred == Ytest)))

Test Set Score: 0.9736842105263158


END OF PROJECT :)